apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: baremetalmachineproviderspecs.baremetal.cluster.k8s.io
spec:
  group: baremetal.cluster.k8s.io
  names:
    kind: BareMetalMachineProviderSpec
    plural: baremetalmachineproviderspecs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        hostSelector:
          description: HostSelector specifies matching criteria for labels on BareMetalHosts.
            This is used to limit the set of BareMetalHost objects considered for
            claiming for a Machine.
          properties:
            matchExpressions:
              description: Label match expressions that must be true on a chosen BareMetalHost
              items:
                properties:
                  key:
                    type: string
                  operator:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - key
                - operator
                - values
                type: object
              type: array
            matchLabels:
              description: Key/value pairs of labels that must exist on a chosen BareMetalHost
              type: object
          type: object
        image:
          description: Image is the image to be provisioned.
          properties:
            checksum:
              description: Checksum is a md5sum value or a URL to retrieve one.
              type: string
            url:
              description: URL is a location of an image to deploy.
              type: string
          required:
          - url
          - checksum
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        userData:
          description: UserData references the Secret that holds user data needed
            by the bare metal operator. The Namespace is optional; it will default
            to the Machine's namespace if not specified.
          type: object
      required:
      - image
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
